import os
from mcp.server.fastmcp import FastMCP
import google.generativeai as genai
from PIL import Image
from dotenv import load_dotenv

# 1. Load Environment & API Key
load_dotenv()
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

# 2. Initialize Server
mcp = FastMCP("FloodPulse-Vision")

@mcp.tool()
def analyze_mbagathi_risk(agent_name: str) -> str:
    """Analyzes the agent's cached mission map using Gemini Vision to assess flood risk."""
    
    # Path logic to find the map generated by static_mapper.py
    script_dir = os.path.dirname(os.path.abspath(__file__))
    map_path = os.path.join(script_dir, f"{agent_name}_on_mission.png")

    if not os.path.exists(map_path):
        return f"❌ Error: No mission map found for {agent_name} at {map_path}."

    try:
        # Load the image for the model
        img = Image.open(map_path)
        
        # Initialize Gemini 2.5 Flash
        model = genai.GenerativeModel('gemini-2.5-flash') 
        
        # The Strategic Prompt
        prompt = f"""
        You are a hydrological risk AI for FloodPulse Nairobi. 
        The image provided is a satellite map of the Mbagathi River basin.
        The agent '{agent_name}' is located at the center of this map (marked by their icon).
        
        Task:
        1. Identify the nearest river/riparian corridor.
        2. Evaluate if the agent's current position is a 'Sump' (low point like T-Mall) or a 'Ridge'.
        3. Provide a brief safety recommendation in a calm, authoritative tone.
        """

        # Generate the perception report
        response = model.generate_content([prompt, img])
        
        return f"🛰️ VISION REPORT FOR {agent_name.upper()}:\n\n{response.text}"

    except Exception as e:
        return f"⚠️ Perception Error: {str(e)}"

if __name__ == "__main__":
    mcp.run()